services:

  pagamentosapp:
    container_name: pagamentos
    build:
      context: .
      dockerfile: project/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=dbPagamentos
    depends_on:
      - dbPagamentos

  dbPagamentos:
    container_name: dbPagamentos
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
